server:
  port: 8081
spring:
  application:
    name: "apply_service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
routes:
  paths:
    saveApply: "/api/v1/apply"
    ListApplys: "/api/v1/apply"
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_db"
    schema: "public"
    username: "postgres"
    password: "0123456"
logging:
  level:
    root: INFO
    com.crediya: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
jwt:
  secret: "miClaveSuperSecretaDeMasDe32CaracteresSeguro123!"
  expiration: 3600000
